###create user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "admin@test.com",
    "password": "pass123",
    "username": "usernameTest",
    "name": "FirstName",
    "lastName": "LastName"
}

###log in user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "admin@test.com",
    "password": "123"
}

###get currently signed in user
GET http://localhost:3000/auth/whoami

###sign out user
POST http://localhost:3000/auth/signout

###get user with a particular id
GET http://localhost:3000/auth/2

###find all users with a given email
GET http://localhost:3000/auth?email=da@test.com

###delete user with a particular id
DELETE http://localhost:3000/auth/1

###edit user with a particular id
PATCH http://localhost:3000/auth/44
content-type: application/json

{
    "email":"da@test.com"
}
