###create user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "qqqqqqqqqqqq@test.com",
    "password": "password123"
}

###log in user
POST http://localhost:3000/auth/sigin
content-type: application/json

{
    "email": "qqqqqqqqqqqq@test.com",
    "password": "password123"
}

###get user with a particular id
GET http://localhost:3000/auth/2

###find all users with a given email
GET http://localhost:3000/auth?email=da@test.com

###delete user with a particular id
DELETE http://localhost:3000/auth/1

###edit user with a particular id
PATCH http://localhost:3000/auth/44
content-type: application/json

{
    "email":"da@test.com"
}